@ECHO OFF
@SETLOCAL ENABLEDELAYEDEXPANSION

REM This file serves as a translation/setup layer for windows scripts. It reads in the
REM variables from the configuration file in the root of the repo, and outputs them as
REM SET commands in a batch file. It then outputs paths based on the settings in that
REM batch file. The main reason for this file is because batch scripting with delayed
REM expansion can only go one level deep. Paths that are derivatives of other dynamic
REM paths just don't work. It's easier to build them here, then use them in the various
REM other scripts (configure.cmd, download.bat, quarto-bld.cmd).

REM Reads the configuration file line by line
REM and convert any export statements into set statements
REM (allows reuse of variables)

SET "FIND=export "
SET REPLACE=

SET OUTFILE="%~dp0\..\..\win_configuration.bat"

REM NOTE: This line is overwriting the existing file, so we start fresh
ECHO REM This file is generated by the package/src/store_win_configuration.bat script. > !OUTFILE!
ECHO REM   Do not edit it manually.  >> !OUTFILE!

FOR /F "tokens=*" %%A IN (%~dp0\..\..\configuration) DO (
  SET LINE=%%A

  IF "!LINE:~0,7!"=="%FIND%" (
    ECHO SET "!LINE:%FIND%=%REPLACE%!" >> !OUTFILE!
  )
)

echo SET "WIN_CONFIG_TRANSLATED=1" >> !OUTFILE!

echo set "QUARTO_ROOT=%%~dp0" >> !OUTFILE!

:: Full paths are what the Quarto code uses internally. You should never see a _DIR entry in there.
::    Note that the conda recipe defines these itself, so these are just for the
::    zip file archives that we build.

:: These are the paths within the Quarto source tree - the "package" subfolder.
echo set "QUARTO_SRC_PATH=%%~dp0\src" >> !OUTFILE!
echo set "QUARTO_PACKAGE_PATH=%%~dp0\%%QUARTO_PACKAGE_DIR%%" >> !OUTFILE!

:: These paths end up in the output package or conda build prefix.
echo set "QUARTO_DIST_PATH=%%~dp0\%%QUARTO_PACKAGE_DIR%%\%%QUARTO_DIST_DIR%%" >> !OUTFILE!
echo set "QUARTO_SHARE_PATH=%%~dp0\%%QUARTO_PACKAGE_DIR%%\%%QUARTO_DIST_DIR%%\%%QUARTO_SHARE_DIR%%" >> !OUTFILE!
echo set "QUARTO_BIN_PATH=%%~dp0\%%QUARTO_PACKAGE_DIR%%\%%QUARTO_DIST_DIR%%\%%QUARTO_BIN_DIR%%" >> !OUTFILE!

echo "Translated/recorded configuration settings from unix configuration script"
